version: "3.8"

services:
    alerts_django:
        build: .
        container_name: alerts_django
        image: alertcontainer525.azurecr.io/alerts_django
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres
        container_name: db
        env_file:
            - ./crypto/.env
        volumes:
         - data:/var/lib/posgresql/data

volumes:
  data:

