# Generated by Django 3.2.12 on 2022-10-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_asset_name', models.CharField(max_length=30)),
                ('alert_value', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('currency', models.CharField(max_length=30)),
                ('alert_when_increases', models.BooleanField(default=True)),
            ],
        ),
    ]
