# Generated by Django 3.2.12 on 2022-10-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='value_when_created',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
