# Generated by Django 3.2.12 on 2022-10-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_alert_value_when_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='value_when_created',
        ),
    ]
