# Generated by Django 3.2.12 on 2022-11-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_remove_alert_value_when_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
