# Generated by Django 3.2.12 on 2022-11-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_alert_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='on_email',
            field=models.BooleanField(default=True),
        ),
    ]
